#!/usr/bin/env ruby
#
# This script downloads historic data for specific symbols from IB

require 'bundler/setup'
require 'ib-api'
require 'symbols'
require 'extensions/verify'
require 'extensions/eod'

# Definition of what we want data for.  We have to keep track of what ticker id
# corresponds to what symbol ourselves, because the ticks don't include any other
# identifying information. The choice of ticker ids is, as far as I can tell, arbitrary.
# Predefined Symbol-definitions -->  lib/ib/symbols
contracts = [ IB::Symbols::Futures.mini_dax,	
              IB::Stock.new( symbol: 'BAS',  currency: 'EUR') ,  # BASF
              IB::Symbols::Forex.eurusd 
						]


# Connect to IB TWS.
#ib = IB::Connection.new( :client_id => 1102, port: 7496, host: '10.222.148.177'  ) do  | gw | 
ib = IB::Connection.new :client_id => 1112, :port => 7496  do | gw | #, :port => 7497 # TWS

	# Subscribe to TWS alerts/errors
	gw.subscribe(:Alert, :ManagedAccounts) { |msg| puts msg.to_human }

end
 contracts.each do | c |
	 c.eod( duration: '10 d',  to: Date.today){|y| y.each{|z| puts z.to_human}}
 end

puts "\n******** Press <Enter> to exit... *********\n\n"
STDIN.gets


