#!/usr/bin/env ruby
#
## This script places WFC buy order for 100 lots
#
## RUN ONLY ON A DEMO ACCOUNT
require 'bundler/setup'
require 'ib-api'
require 'order-prototypes'

# Only for Advisor accounts: you need to provide account_code such as U666777
account_code = ARGV[0] || ''
#
# First, connect to IB TWS. Arbitrary :client_id is used to identify your script
ib = IB::Connection.new client_id: 1112  do | gw | #, :port => 7496 # TWS

# Subscribe to TWS alerts/errors and order-related messages prior to the connection of the client
  gw.subscribe(:Alert, :OpenOrder, :OrderStatus,  :ContractDataEnd, :ManagedAccounts ) { |msg| puts msg.to_human }
  gw.subscribe(:ContractData ) do |msg| 
    puts msg.contract.to_human + "\n"
  end

end
wfc = IB::Stock.new symbol: 'WFC'
ib.send_message :RequestContractData, id: 56, contract: wfc

puts IB::Limit.summary
puts "Supported Parameter \n -------------------------- "
puts IB::Limit.parameters
buy_order = IB::Limit.order size: 100,
                          price: 1 + rand().round(2),
                          action:  :buy,
													account: account_code
puts buy_order.to_human
ib.wait_for :NextValidId
ib.place_order buy_order,  wfc
ib.wait_for :ContractDataEnd, 5 #sec

ib.send_message :RequestAllOpenOrders

puts "\n******** Press <Enter> to cancel... *********\n\n"
STDIN.gets


## RUN ONLY ON A DEMO ACCOUNT
#
#
# expected output
=begin
./place_limit_order DU167349
Connected to server, version: 137,
 connection time: 2020-09-03 05:21:47 +0000 local, 2020-09-03T05:21:47+00:00 remote.
< ManagedAccounts: DF167347 - DU167348 - DU167349>
Got next valid order id: 68.
TWS Warning 2104: Market data farm connection is OK:eufarm
TWS Warning 2104: Market data farm connection is OK:usopt
TWS Warning 2104: Market data farm connection is OK:usfarm
TWS Warning 2107: HMDS data farm connection is inactive but should be available upon demand.euhmds
	A Limit order is an order to buy or sell at a specified price or better. 
	The Limit order ensures that if the order fills, it will not fill at a price less favorable than 
	your limit price, but it does not guarantee a fill. 
	It appears in the orderbook.
Supported Parameter 
 -------------------------- 
Required : action --> {"B"=>:buy, "S"=>:sell, "T"=>:short, "X"=>:short_exempt}
	: total_quantity --> also aliased as :size
	: limit_price --> also aliased as :price
 --------------- 
Optional : account --> Account(number) to trade on
 --------------- 
<Order: LMT GTC buy 100  @ 1.43 New #/ from /DU167349>
<Stock: WFC USD NYSE>
<ContractDataEnd: request_id 56 >

******** Press <Enter> to cancel... *********

<OpenOrder: <Stock: WFC USD> <Order: LMT GTC buy 100.0  @ 1.45 PreSubmitted #67/1750019077 from 1112/DU167349>>
<OrderState: PreSubmitted #67/1750019077 from 1112 filled 0.0/100.0 at 0.0/0.0 why_held locate>
<OrderState: ApiPending #68/0 from 1112 filled 0.0/100.0>
No subscribers for message IB::Messages::Incoming::OpenOrderEnd!
<OpenOrder: <Stock: WFC USD> <Order: LMT GTC buy 100.0  @ 1.43 PreSubmitted #68/1750019078 from 1112/DU167349>>
<OrderState: PreSubmitted #68/1750019078 from 1112 filled 0.0/100.0 at 0.0/0.0 why_held locate>

=end
