#!/usr/bin/env ruby
#
# This script places a combo order:  Buy Microsoft, sell WellsFarge for 32$
# (Marketprice : 40$ (Mar 2018))

require 'bundler/setup'
require 'ib-api'
require 'order-prototypes'
require 'symbols'

# Utility method that helps us build multi-legged (BAG) Orders
def spread *contracts

	ib = IB::Connection.current
	tws_contracts =  contracts.map.with_index do |c, i|
		ib.clear_received :ContractData, :ContractDataEnd
		ib.send_message :RequestContractData, :id => i+1, :contract => c
		ib.wait_for :ContractDataEnd, 3
		ib.received[:ContractData].last.contract
	end
	con_ids =  tws_contracts.map &:con_id
	bag_symbol =  tws_contracts.map( &:symbol ).join(',')
	weights =  block_given? ? yield  : Array.new(contracts.size,1)

	legs = con_ids.zip(weights).map do |con_id, weight|
		IB::ComboLeg.new con_id: con_id, weight: weight  
	end

	# Create and return new Combo contract
	IB::Bag.new :symbol => bag_symbol,
		:currency => tws_contracts.first.currency,   
		:exchange => "SMART",
		:combo_legs => legs
end
# Only for Advisor accounts: you need to provide account_code such as U666777
account_code = ARGV[0] || ''

# 
# First, connect to IB TWS. Arbitrary :client_id is used to identify your script
ib = IB::Connection.new :client_id => 1112 do | gw | #, :port => 7497 # TWS

# Subscribe to TWS alerts/errors and order-related messages
	gw.subscribe(:Alert, :OpenOrder, :OrderStatus) { |msg| puts msg.to_human }
end

# if tws/gateway is ready
ib.wait_for :NextValidId

# create the bag
the_bag = spread( IB::Symbols::Stocks.msft, IB::Symbols::Stocks.wfc ){ [1, -1]  }

puts the_bag.inspect
# use the order-prototype to create the order
order = IB::Combo.order total_quantity: 10, 
                      limit_price: 32,
                      action: :buy,
											account: account_code 
		
# and place both
ib.place_order order,the_bag 

ib.wait_for [:OpenOrder, 3], [:OrderStatus, 2]

puts "\n******** Press <Enter> to cancel... *********\n\n"
STDIN.gets

=begin
Expected output 
 ./place_combo_order DU167349
Connected to server, version: 137,
 connection time: 2020-09-03 05:17:45 +0000 local, 2020-09-03T05:17:44+00:00 remote.
No subscribers for message IB::Messages::Incoming::ManagedAccounts!
Got next valid order id: 66.
TWS Warning 2104: Market data farm connection is OK:eufarm
TWS Warning 2104: Market data farm connection is OK:usopt
TWS Warning 2104: Market data farm connection is OK:usfarm
TWS Warning 2107: HMDS data farm connection is inactive but should be available upon demand.euhmds
No subscribers for message IB::Messages::Incoming::ContractData!
No subscribers for message IB::Messages::Incoming::ContractDataEnd!
No subscribers for message IB::Messages::Incoming::ContractData!
No subscribers for message IB::Messages::Incoming::ContractDataEnd!
#<IB::Bag:0x0000000000d0a7a0 @attributes={:symbol=>"MSFT,WFC", :currency=>"USD", :exchange=>"SMART", :created_at=>2020-09-03 05:17:45 +0000, :right=>"", :include_expired=>false, :sec_type=>"BAG"}, @combo_legs=[#<IB::ComboLeg:0x0000000000b92260 @attributes={:con_id=>272093, :side=>"B", :ratio=>1, :created_at=>2020-09-03 05:17:45 +0000, :open_close=>0, :short_sale_slot=>0, :designated_location=>"", :exchange=>"SMART", :exempt_code=>-1}>, #<IB::ComboLeg:0x0000000000d0b5d8 @attributes={:con_id=>10375, :side=>"S", :ratio=>1, :created_at=>2020-09-03 05:17:45 +0000, :open_close=>0, :short_sale_slot=>0, :designated_location=>"", :exchange=>"SMART", :exempt_code=>-1}>]>
<OpenOrder: <Bag: MSFT,WFC SMART USD legs: 10375|-1,272093|1 > <Order: LMT GTC buy 10.0  @ 32.0 PreSubmitted #66/1750019076 from 1112/DU167349>>
<OrderState: PreSubmitted #66/1750019076 from 1112 filled 0.0/10.0 at 0.0/0.0 why_held locate>

******** Press <Enter> to cancel... *********

./cancel_orders 
< ManagedAccounts: DF167347 - DU167348 - DU167349>
TWS Warning 2104: Market data farm connection is OK:eufarm
TWS Warning 2104: Market data farm connection is OK:usopt
TWS Warning 2104: Market data farm connection is OK:usfarm
TWS Warning 2107: HMDS data farm connection is inactive but should be available upon demand.euhmds
-------------------------------------------------------
Remaining Orders
-------------------------------------------------------
<OpenOrder: <Bag: MSFT,WFC SMART USD legs: 10375|-1,272093|1 > <Order: LMT GTC buy 10.0  @ 32.0 PendingCancel #66/1750019076 from 1112/DU167349>>
<OrderState: PendingCancel #66/1750019076 from 1112 filled 0.0/10.0 at 0.0/0.0 why_held >
<OpenOrderEnd: >


=end
