
module IB
  module Messages
    module Outgoing
      extend Messages # def_message macros

      ## actual Version supported is: 137
      ## changes:   MIN_SERVER_VER_SMART_DEPTH: 146  --> insert 'is_smarth_depth' after 'num_rows'
      ##  then: 'is_smart_depth' (bool) has to be specified in  CancelMarketDepth, too
      #
      #
      CancelMarketDepth = def_message([11, 1], :is_smart_depth)

      RequestMarketDepth = def_message(
        [10, 5],
        :request_id,   # autogenerated if not specified
        [:contract, :serialize, :option, :trading_class],  # serialize_supershort],
        :num_rows,
        :is_smart_depth,
        ""
      )  #  mktDataOptionsStr. ## not supported by api

      class RequestMarketDepth
        def encode
          ## create a proper request_id  and erase :id and :ticker_id if nessesary
          if self.class.properties?.include?(:request_id)
            @data[:request_id] = @data[:id] || @data[:ticker_id] || @data[:request_id] || rand(9999)
            @data[:id] = @data[:ticker_id] = nil
          end
          contract = @data[:contract]
#          error "RequestMarketDepth requires a valid con-id" if contract.con_id.empty?

          [
            self.class.message_id,
            self.class.version,
            @data[:request_id],
            contract.con_id,
            contract.symbol,
            contract[:sec_type],
            contract.expiry,  #last_trade_date_or_contract_month,
            contract.strike,
            contract.right == :none ? '' : contract.right,
            contract.multiplier,
            contract.exchange,
            contract.primary_exchange,
            contract.currency,
            contract.local_symbol,
            contract.trading_class,
            @data[:num_rows],
            @data[:is_smart_depth],
            "",
            ""
          ]
        end
      end
    end
  end
end
