# The Futures module tries to guess the front month future using a crude algorithm that
# does not take into account expiry/rollover day. This will be valid most of the time,
# but near/after expiry day the next quarter's contract takes over as the volume leader.

module IB
  module Symbols
    module Futures
      extend Symbols


      def self.contracts
  @contracts.presence ||( super.merge  :ym => IB::Future.new(:symbol => "YM",
                                  :expiry => IB::Future.next_expiry,
                                  :exchange => "CBOT",
                                  :currency => "USD",
                                  :description => "Mini-DJIA future"),
         :nq => IB::Future.new(:symbol => "NQ",
                                  :expiry => IB::Future.next_expiry,
                                  :exchange => "CME",
                                  :currency => "USD",
                                  :multiplier => 20,
                                  :description => "Mini Nasdaq 100 future"),
         :micro_nq => IB::Future.new(:symbol => "MNQ",
                                  :expiry => IB::Future.next_expiry,
                                  :exchange => "CME",
                                  :currency => "USD",
                                  :multiplier => 2,
                                  :description => "Micro Nasdaq 100 future"),
         :es => IB::Future.new(:symbol => "ES",
                                  :expiry => IB::Future.next_expiry,
                                  :exchange => "CME",
                                  :currency => "USD",
                                  :multiplier => 50,
                                  :description => "Mini S&P 500 future"),
         :micro_es => IB::Future.new(:symbol => "MES",
                                  :expiry => IB::Future.next_expiry,
                                  :exchange => "CME",
                                  :currency => "USD",
                                  :multiplier => 5,
                                  :description => "Micro S&P 500 future"),
         :russell => IB::Future.new(:symbol => "RTY",
                                  :expiry => IB::Future.next_expiry,
                                  :exchange => "CME",
                                  :currency => "USD",
                                  :multiplier => 5,
                                  :description => "Mini Russell 2000 future"),
         :micro_russell => IB::Future.new(:symbol => "M2K",
                                  :expiry => IB::Future.next_expiry,
                                  :exchange => "CME",
                                  :currency => "USD",
                                  :multiplier => 5,
                                  :description => "Micro Russell 2000 future"),
        :zn => IB::Future.new( symbol: 'ZN',
                              expiry: IB::Future.next_expiry,
                              currency: 'USD',
                              multiplier: 1000,
                              exchange: 'CBOT',
                              description: 'US Treasury Note -- 10 Years'),
        :zb => IB::Future.new( symbol: 'ZB',
                              expiry: IB::Future.next_expiry,
                              currency: 'USD',
                              multiplier: 1000,
                              exchange: 'CBOT',
                              description: 'US Treasury Note -- 30 Years'),
        :micro_dax => IB::Future.new( symbol: 'DAX', exchange: 'EUREX',
                                  expiry:  IB::Future.next_expiry,
                                  currency: 'EUR',
                                  multiplier: 1,
                                  description: 'Mini DAX-Future'),
        :mini_dax => IB::Future.new( symbol: 'DAX', exchange: 'EUREX',
                                  expiry:  IB::Future.next_expiry,
                                  currency: 'EUR',
                                  multiplier: 5,
                                  description: 'Mini DAX-Future'),
        :dax => IB::Future.new( symbol: 'DAX', exchange: 'EUREX',
                                  expiry:  IB::Future.next_expiry,
                                  currency: 'EUR',
                                  multiplier: 25,
                                  description: 'DAX-Future'),
        :stoxx=> IB::Future.new( symbol: 'ESTX50', exchange: 'EUREX',
                                  expiry:  IB::Future.next_expiry,
                                  currency: 'EUR',
                                  multiplier: 10,
                                  description: 'EuroStoxx 50 -Future'),
        :mini_stoxx=> IB::Future.new( symbol: 'ESTX50', exchange: 'EUREX',
                                  expiry:  IB::Future.next_expiry,
                                  currency: 'EUR',
                                  multiplier: 1,
                                  description: 'Mini/Micro EuroStoxx 50 -Future'),
        :micro_stoxx=> IB::Future.new( symbol: 'ESTX50', exchange: 'EUREX',
                                  expiry:  IB::Future.next_expiry,
                                  currency: 'EUR',
                                  multiplier: 1,
                                  description: 'Miico EuroStoxx 50 -Future'),
        :gbp => IB::Future.new(:symbol => "GBP",
                                 :expiry => IB::Future.next_expiry,
                                 :exchange => "CME",
                                 :currency => "USD",
                                 :multiplier => 62500,
                                 :description => "British Pounds future"),
         :eur => IB::Future.new(:symbol => "EUR",
                                  :expiry => IB::Future.next_expiry,
                                  :exchange => "CME",
                                  :currency => "USD",
                                  :multiplier => 12500,
                                  :description => "Euro FX future"),
         :jpy => IB::Future.new(:symbol => "JPY",
                                  :expiry => IB::Future.next_expiry,
                                  :exchange => "CME",
                                  :currency => "USD",
                                  :multiplier => 12500000,
                                  :description => "Japanese Yen future"),
         :hsi => IB::Future.new(:symbol => "HSI",
                                  :expiry => IB::Future.next_expiry,
                                  :exchange => "HKFE",
                                  :currency => "HKD",
                                  :multiplier => 50,
                                  :description => "Hang Seng Index future"),
         :vix => IB::Future.new(:symbol => "VIX",
                                  :expiry => IB::Future.next_expiry,
                                  :exchange => "CFE",
                                  :currency => "USD",
                                  :description => "CBOE Volatility Index future"))
      end
    end
  end
end
